kind: Secret
apiVersion: v1
metadata:
  name: backend-secrets
  namespace: chat-app
type: Opaque
data:
  jwt_secret_key: c2VjdXJlSld0U2VjcmV0S2V5MTIzIQ== # 'secureJWTSecretKey123!' base64 encoded
  mongodb_url: bW9uZ29kYjovL3Jvb3Q6YWRtaW5AbW9uZ29kYi1zZXJ2aWNlOjI3MDE3L2NoYXRBcHA/YXV0aFNvdXJjZT1hZG1pbg== # mongodb://root:admin@mongodb-service:27017/chatApp?authSource=admin to base64